DELETE FROM pht_code
WHERE client_id=1 AND type_cd = '1013';
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-1010', NULL, NULL, 'Greenld', 'Greenland', 10, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-1220', NULL, NULL, 'Canada', 'Canada', 20, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-1610', NULL, NULL, 'Sp Mqel', 'St Pierre and Miquelon', 30, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2010', NULL, NULL, 'Mexico', 'Mexico', 40, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2050', NULL, NULL, 'Guatmal', 'Guatemala', 50, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2080', NULL, NULL, 'Belize', 'Belize', 60, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2110', NULL, NULL, 'Salvadr', 'El Salvador', 70, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2150', NULL, NULL, 'Hondura', 'Honduras', 80, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2190', NULL, NULL, 'Nicarag', 'Nicaragua', 90, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2230', NULL, NULL, 'C Rica', 'Costa Rica', 100, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2250', NULL, NULL, 'Panama', 'Panama', 110, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2320', NULL, NULL, 'Bermuda', 'Bermuda', 120, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2360', NULL, NULL, 'Bahamas', 'Bahamas', 130, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2390', NULL, NULL, 'Cuba', 'Cuba', 140, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2410', NULL, NULL, 'Jamaica', 'Jamaica', 150, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2430', NULL, NULL, 'Turk Is', 'Turks and Caicos Islands', 160, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2440', NULL, NULL, 'Cayman', 'Cayman Islands', 170, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2450', NULL, NULL, 'Haiti', 'Haiti', 180, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2470', NULL, NULL, 'Dom Rep', 'Dominican Republic', 190, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2481', NULL, NULL, 'Anglla', 'Anguilla', 200, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2482', NULL, NULL, 'B Virgn', 'British Virgin Islands', 210, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2483', NULL, NULL, 'St K N', 'St Kitts and Nevis', 220, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2484', NULL, NULL, 'Antigua', 'Antigua and Barbuda', 230, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2485', NULL, NULL, 'Monsrat', 'Montserrat', 240, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2486', NULL, NULL, 'Dominca', 'Dominica', 250, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2487', NULL, NULL, 'S Lucia', 'St Lucia', 260, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2488', NULL, NULL, 'S Vn Gr', 'St Vincent and the Grenadines', 270, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2489', NULL, NULL, 'Grenada', 'Grenada', 280, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2720', NULL, NULL, 'Barbado', 'Barbados', 290, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2740', NULL, NULL, 'Trinid', 'Trinidad and Tobago', 300, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2771', NULL, NULL, 'N Antil', 'Netherlands Antilles', 310, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2779', NULL, NULL, 'Aruba', 'Aruba', 320, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2831', NULL, NULL, 'Guadlpe', 'Guadeloupe', 330, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-2839', NULL, NULL, 'Martinq', 'Martinique', 340, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3010', NULL, NULL, 'Colomb', 'Colombia', 350, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3070', NULL, NULL, 'Venez', 'Venezuela', 360, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3120', NULL, NULL, 'Guyana', 'Guyana', 370, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3150', NULL, NULL, 'Surinam', 'Suriname', 380, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3170', NULL, NULL, 'F Guian', 'French Guiana', 390, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3310', NULL, NULL, 'Ecuador', 'Ecuador', 400, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3330', NULL, NULL, 'Peru', 'Peru', 410, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3350', NULL, NULL, 'Bolivia', 'Bolivia', 420, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3370', NULL, NULL, 'Chile', 'Chile', 430, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3510', NULL, NULL, 'Brazil', 'Brazil', 440, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3530', NULL, NULL, 'Paragua', 'Paraguay', 450, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3550', NULL, NULL, 'Uruguay', 'Uruguay', 460, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3570', NULL, NULL, 'Argent', 'Argentina', 470, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-3720', NULL, NULL, 'Falk Is', 'Falkland Islands', 480, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4000', NULL, NULL, 'Iceland', 'Iceland', 490, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4010', NULL, NULL, 'Sweden', 'Sweden', 500, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4031', NULL, NULL, 'Sv Jm I', 'Svalbard, Jan Mayen Island', 510, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4039', NULL, NULL, 'Norway', 'Norway', 520, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4050', NULL, NULL, 'Finland', 'Finland', 530, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4091', NULL, NULL, 'Faroe', 'Faroe Islands', 540, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4099', NULL, NULL, 'Denmark', 'Denmark', 550, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4120', NULL, NULL, 'U King', 'United Kingdom', 560, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4190', NULL, NULL, 'Ireland', 'Ireland', 570, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4210', NULL, NULL, 'Nethlds', 'Netherlands', 580, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4231', NULL, NULL, 'Belgium', 'Belgium', 590, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4239', NULL, NULL, 'Luxmbrg', 'Luxembourg', 600, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4271', NULL, NULL, 'Andorra', 'Andorra', 610, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4272', NULL, NULL, 'Monaco', 'Monaco', 620, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4279', NULL, NULL, 'France', 'France', 630, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4280', NULL, NULL, 'Fr Germ', 'Federal Republic of Germany', 640, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4330', NULL, NULL, 'Austria', 'Austria', 650, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4351', NULL, NULL, 'Czech', 'Czech Republic', 660, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4359', NULL, NULL, 'Slovak', 'Slovakia', 670, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4370', NULL, NULL, 'Hungary', 'Hungary', 680, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4411', NULL, NULL, 'Lichten', 'Liechtenstein', 690, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4419', NULL, NULL, 'Switzld', 'Switzerland', 700, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4470', NULL, NULL, 'Estonia', 'Estonia', 710, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4490', NULL, NULL, 'Latvia', 'Latvia', 720, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4510', NULL, NULL, 'Lithuan', 'Lithuania', 730, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4550', NULL, NULL, 'Poland', 'Poland', 740, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4621', NULL, NULL, 'Russia', 'Russia', 750, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4622', NULL, NULL, 'Belar', 'Belarus', 760, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4623', NULL, NULL, 'Ukraine', 'Ukraine', 770, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4631', NULL, NULL, 'Armenia', 'Armenia', 780, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4632', NULL, NULL, 'Azerbjn', 'Azerbaijan', 790, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4633', NULL, NULL, 'Georgia', 'Georgia', 800, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4634', NULL, NULL, 'Kazakhs', 'Kazakhstan', 810, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4635', NULL, NULL, 'Kyrgyzs', 'Kyrgyzstan', 820, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4641', NULL, NULL, 'Moldova', 'Moldova', 830, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4642', NULL, NULL, 'Tajikis', 'Tajikistan', 840, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4643', NULL, NULL, 'Turkmen', 'Turkmenistan', 850, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4644', NULL, NULL, 'Uzbekis', 'Uzbekistan', 860, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4700', NULL, NULL, 'Spain', 'Spain', 870, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4710', NULL, NULL, 'Portugl', 'Portugal', 880, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4720', NULL, NULL, 'Gibralt', 'Gibraltar', 890, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4730', NULL, NULL, 'Malta', 'Malta', 900, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4751', NULL, NULL, 'San Mar', 'San Marino', 910, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4752', NULL, NULL, 'Vat Cty', 'Vatican City', 920, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4759', NULL, NULL, 'Italy', 'Italy', 930, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4791', NULL, NULL, 'Croatia', 'Croatia', 940, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4792', NULL, NULL, 'Slvenia', 'Slovenia', 950, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4793', NULL, NULL, 'Bosnia', 'Bosnia-Hercegovina', 960, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4794', NULL, NULL, 'Macedon', 'Macedonia (Skopje)', 970, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4801', NULL, NULL, 'Serbia', 'Serbia', 980, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4803', NULL, NULL, 'Kosovo', 'Kosovo', 990, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4804', NULL, NULL, 'Montene', 'Montenegro', 1000, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4810', NULL, NULL, 'Albania', 'Albania', 1010, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4840', NULL, NULL, 'Greece', 'Greece', 1020, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4850', NULL, NULL, 'Romania', 'Romania', 1030, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4870', NULL, NULL, 'Bulgar', 'Bulgaria', 1040, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4890', NULL, NULL, 'Turkey', 'Turkey', 1050, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-4910', NULL, NULL, 'Cyprus', 'Cyprus', 1060, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5020', NULL, NULL, 'Syria', 'Syria', 1070, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5040', NULL, NULL, 'Lebanon', 'Lebanon', 1080, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5050', NULL, NULL, 'Iraq', 'Iraq', 1090, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5070', NULL, NULL, 'Iran', 'Iran', 1100, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5081', NULL, NULL, 'Israel', 'Israel', 1110, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5082', NULL, NULL, 'Gaza', 'Gaza Strip Administered by Israel', 1120, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5083', NULL, NULL, 'Westbnk', 'West Bank Administered by Israel', 1130, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5110', NULL, NULL, 'Jordan', 'Jordan', 1140, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5130', NULL, NULL, 'Kuwait', 'Kuwait', 1150, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5170', NULL, NULL, 'S Arab', 'Saudi Arabia', 1160, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5180', NULL, NULL, 'Qatar', 'Qatar', 1170, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5200', NULL, NULL, 'Arab Em', 'United Arab Emirates', 1180, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5210', NULL, NULL, 'Yemen', 'Republic of Yemen', 1190, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5230', NULL, NULL, 'Oman', 'Oman', 1200, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5250', NULL, NULL, 'Bahrain', 'Bahrain', 1210, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5310', NULL, NULL, 'Afghan', 'Afghanistan', 1220, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5330', NULL, NULL, 'India', 'India', 1230, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5350', NULL, NULL, 'Pakistn', 'Pakistan', 1240, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5360', NULL, NULL, 'Nepal', 'Nepal', 1250, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5380', NULL, NULL, 'Bngldsh', 'Bangladesh', 1260, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5420', NULL, NULL, 'Sri Lka', 'Sri Lanka', 1270, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5460', NULL, NULL, 'Burma', 'Burma (Myanmar)', 1280, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5490', NULL, NULL, 'Thailnd', 'Thailand', 1290, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5520', NULL, NULL, 'Vietnam', 'Vietnam', 1300, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5530', NULL, NULL, 'Laos', 'Laos', 1310, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5550', NULL, NULL, 'Cambod', 'Cambodia', 1320, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5570', NULL, NULL, 'Malaysa', 'Malaysia', 1330, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5590', NULL, NULL, 'Singapr', 'Singapore', 1340, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5600', NULL, NULL, 'Indnsia', 'Indonesia', 1350, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5601', NULL, NULL, 'Etimor', 'Timor-Leste', 1360, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5610', NULL, NULL, 'Brunei', 'Brunei', 1370, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5650', NULL, NULL, 'Phil R', 'Philippines', 1380, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5660', NULL, NULL, 'Macao', 'Macao', 1390, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5682', NULL, NULL, 'Bhutan', 'Bhutan', 1400, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5683', NULL, NULL, 'Maldive', 'Maldives', 1410, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5700', NULL, NULL, 'China', 'China', 1420, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5740', NULL, NULL, 'Mongola', 'Mongolia', 1430, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5790', NULL, NULL, 'No Kor', 'North Korea', 1440, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5800', NULL, NULL, 'Kor Rep', 'Korea, South', 1450, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5820', NULL, NULL, 'Hg Kong', 'Hong Kong', 1460, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5830', NULL, NULL, 'Taiwan', 'Taiwan', 1470, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-5880', NULL, NULL, 'Japan', 'Japan', 1480, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6021', NULL, NULL, 'Austral', 'Australia', 1490, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6022', NULL, NULL, 'Norfolk', 'Norfolk Island', 1500, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6023', NULL, NULL, 'Cocos I', 'Cocos (Keeling) Island', 1510, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6024', NULL, NULL, 'Crist I', 'Christmas Island', 1520, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6029', NULL, NULL, 'Heard I', 'Heard and Mcdonald Islands', 1530, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6040', NULL, NULL, 'New Gui', 'Papua New Guinea', 1540, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6141', NULL, NULL, 'N Zeal', 'New Zealand', 1550, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6142', NULL, NULL, 'Cook Is', 'Cook Islands', 1560, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6143', NULL, NULL, 'Tokelau', 'Tokelau', 1570, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6144', NULL, NULL, 'Niue', 'Niue', 1580, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6150', NULL, NULL, 'W Samoa', 'Western Samoa', 1590, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6223', NULL, NULL, 'Solmn I', 'Solomon Islands', 1600, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6224', NULL, NULL, 'Vanuatu', 'Vanuatu', 1610, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6225', NULL, NULL, 'Pitcarn', 'Pitcairn Island', 1620, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6226', NULL, NULL, 'Kiribat', 'Kiribati', 1630, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6227', NULL, NULL, 'Tuvalu', 'Tuvalu', 1640, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6412', NULL, NULL, 'N Caldn', 'New Caledonia', 1650, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6413', NULL, NULL, 'Wallis', 'Wallis and Futuna', 1660, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6414', NULL, NULL, 'Fr Poly', 'French Polynesia', 1670, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6810', NULL, NULL, 'Marshal', 'Marshall Islands', 1680, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6820', NULL, NULL, 'Microns', 'Federated States of Micronesia', 1690, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6830', NULL, NULL, 'Palau', 'Palau', 1700, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6862', NULL, NULL, 'Nauru', 'Nauru', 1710, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6863', NULL, NULL, 'Fiji', 'Fiji', 1720, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-6864', NULL, NULL, 'Tonga', 'Tonga', 1730, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7140', NULL, NULL, 'Moroc', 'Morocco', 1740, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7210', NULL, NULL, 'Algeria', 'Algeria', 1750, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7230', NULL, NULL, 'Tunisia', 'Tunisia', 1760, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7250', NULL, NULL, 'Libya', 'Libya', 1770, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7290', NULL, NULL, 'Egypt', 'Egypt', 1780, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7320', NULL, NULL, 'Sudan', 'Sudan', 1790, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7370', NULL, NULL, 'W Sahar', 'Western Sahara', 1800, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7380', NULL, NULL, 'Eq Guin', 'Equatorial Guinea', 1810, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7410', NULL, NULL, 'Mauritn', 'Mauritania', 1820, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7420', NULL, NULL, 'Camroon', 'Cameroon', 1830, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7440', NULL, NULL, 'Senegal', 'Senegal', 1840, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7450', NULL, NULL, 'Mali', 'Mali', 1850, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7460', NULL, NULL, 'Guinea', 'Guinea', 1860, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7470', NULL, NULL, 'Sier Ln', 'Sierra Leone', 1870, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7480', NULL, NULL, 'Ivy Cst', 'Cote d''IVOIRE', 1880, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7490', NULL, NULL, 'Ghana', 'Ghana', 1890, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7500', NULL, NULL, 'Gambia', 'Gambia', 1900, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7510', NULL, NULL, 'Niger', 'Niger', 1910, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7520', NULL, NULL, 'Togo', 'Togo', 1920, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7530', NULL, NULL, 'Nigeria', 'Nigeria', 1930, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7540', NULL, NULL, 'C Af Rp', 'Central African Republic', 1940, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7550', NULL, NULL, 'Gabon', 'Gabon', 1950, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7560', NULL, NULL, 'Chad', 'Chad', 1960, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7580', NULL, NULL, 'S Heln', 'St Helena', 1970, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7600', NULL, NULL, 'Burkina', 'Burkina', 1980, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7610', NULL, NULL, 'Benin', 'Benin', 1990, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7620', NULL, NULL, 'Angola', 'Angola', 2000, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7630', NULL, NULL, 'Congo B', 'Congo (Brazzaville)', 2010, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7642', NULL, NULL, 'G Bisau', 'Guinea-Bissau', 2020, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7643', NULL, NULL, 'C Verde', 'Cape Verde', 2030, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7644', NULL, NULL, 'Sao T P', 'Sao Tome and Principe', 2040, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7650', NULL, NULL, 'Liberia', 'Liberia', 2050, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7660', NULL, NULL, 'Congo C', 'Congo (Kinshasa)', 2060, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7670', NULL, NULL, 'Burundi', 'Burundi', 2070, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7690', NULL, NULL, 'Rwanda', 'Rwanda', 2080, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7700', NULL, NULL, 'Somalia', 'Somalia', 2090, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7741', NULL, NULL, 'Eritrea', 'Eritrea', 2100, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7749', NULL, NULL, 'Ethiop', 'Ethiopia', 2110, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7770', NULL, NULL, 'Djibuti', 'Djibouti', 2120, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7780', NULL, NULL, 'Uganda', 'Uganda', 2130, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7790', NULL, NULL, 'Kenya', 'Kenya', 2140, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7800', NULL, NULL, 'Seychel', 'Seychelles', 2150, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7810', NULL, NULL, 'B Ind O', 'British Indian Ocean Territories', 2160, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7830', NULL, NULL, 'Tnzania', 'Tanzania', 2170, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7850', NULL, NULL, 'Maurit', 'Mauritius', 2180, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7870', NULL, NULL, 'Mozambq', 'Mozambique', 2190, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7880', NULL, NULL, 'Madagas', 'Madagascar', 2200, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7881', NULL, NULL, 'Mayotte', 'Mayotte', 2210, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7890', NULL, NULL, 'Comoros', 'Comoros', 2220, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7904', NULL, NULL, 'Reunion', 'Reunion', 2230, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7905', NULL, NULL, 'F So An', 'French Southern and Antarctic Lands', 2240, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7910', NULL, NULL, 'Rep Saf', 'South Africa', 2250, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7920', NULL, NULL, 'Namibia', 'Namibia', 2260, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7930', NULL, NULL, 'Botswan', 'Botswana', 2270, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7940', NULL, NULL, 'Zambia', 'Zambia', 2280, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7950', NULL, NULL, 'Swazlan', 'Swaziland', 2290, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7960', NULL, NULL, 'Zmbabwe', 'Zimbabwe', 2300, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7970', NULL, NULL, 'Malawi', 'Malawi', 2310, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-7990', NULL, NULL, 'Lesotho', 'Lesotho', 2320, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-9110', NULL, NULL, 'Virg Is', 'Virgin Islands of the United States', 2330, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-9350', NULL, NULL, 'Guam', 'Guam', 2340, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-9510', NULL, NULL, 'Am Sam', 'American Samoa', 2350, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-9610', NULL, NULL, 'N Mar I', 'Northern Mariana Islands', 2360, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1013, '1013-9800', NULL, NULL, 'Us O Is', 'Us Minor Outlying Islands', 2370, 'load_table_data', NOW(), NULL);
COMMIT;