DELETE FROM pht_code
WHERE client_id=1 AND type_cd = '1014';
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-01', NULL, NULL, 'Maine', 'Portland Me', 10, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-02', NULL, NULL, 'St Albn', 'St Albans Vt', 20, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-04', NULL, NULL, 'Boston', 'Boston Ma', 30, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-05', NULL, NULL, 'Prov Ri', 'Providence Ri', 40, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-07', NULL, NULL, 'Ogdensb', 'Ogdensburg Ny', 50, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-09', NULL, NULL, 'Buffalo', 'Buffalo Ny', 60, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-10', NULL, NULL, 'Ny City', 'New York City Ny', 70, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-11', NULL, NULL, 'Phila', 'Philadelphia Pa', 80, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-13', NULL, NULL, 'Balt', 'Baltimore Md', 90, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-14', NULL, NULL, 'Norfolk', 'Norfolk Va', 100, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-15', NULL, NULL, 'Wilm Nc', 'Wilmington Nc', 110, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-16', NULL, NULL, 'Chrlstn', 'Charleston Sc', 120, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-17', NULL, NULL, 'Savannh', 'Savannah Ga', 130, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-18', NULL, NULL, 'Tampa', 'Tampa Fl', 140, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-19', NULL, NULL, 'Mobile', 'Mobile Al', 150, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-20', NULL, NULL, 'New Orl', 'New Orleans La', 160, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-21', NULL, NULL, 'Port Ar', 'Port Arthur Tx', 170, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-23', NULL, NULL, 'Laredo', 'Laredo Tx', 180, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-24', NULL, NULL, 'El Paso', 'El Paso Tx', 190, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-25', NULL, NULL, 'San Dgo', 'San Diego Ca', 200, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-26', NULL, NULL, 'Nogales', 'Nogales Az', 210, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-27', NULL, NULL, 'Los Ang', 'Los Angeles Ca', 220, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-28', NULL, NULL, 'San Frn', 'San Francisco Ca', 230, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-29', NULL, NULL, 'Col-Snk', 'Columbia-Snake', 240, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-30', NULL, NULL, 'Seattle', 'Seattle Wa', 250, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-31', NULL, NULL, 'Alaska', 'Anchorage Ak', 260, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-32', NULL, NULL, 'Hawaii', 'Honolulu Hi', 270, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-33', NULL, NULL, 'Gtfalls', 'Great Falls Mt', 280, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-34', NULL, NULL, 'Pembina', 'Pembina Nd', 290, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-35', NULL, NULL, 'Minnpls', 'Minneapolis Mn', 300, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-36', NULL, NULL, 'Duluth', 'Duluth Mn', 310, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-37', NULL, NULL, 'Milwauk', 'Milwaukee Wi', 320, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-38', NULL, NULL, 'Detroit', 'Detroit Mi', 330, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-39', NULL, NULL, 'Chicago', 'Chicago Il', 340, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-41', NULL, NULL, 'Clevlnd', 'Cleveland Oh', 350, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-45', NULL, NULL, 'St Loui', 'St Louis Mo', 360, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-49', NULL, NULL, 'P Rico', 'San Juan Pr', 370, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-51', NULL, NULL, 'Virg Is', 'Virgin Islands', 380, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-52', NULL, NULL, 'Miami', 'Miami Fl', 390, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-53', NULL, NULL, 'Houston', 'Houston Tx', 400, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-54', NULL, NULL, 'Wash Dc', 'Washington Dc', 410, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-55', NULL, NULL, 'Dallas', 'Dallas/Fort Worth Tx', 420, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-60', NULL, NULL, 'Vessels', 'Vessels Own Power', 430, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-70', NULL, NULL, 'Lv Est', 'Shipments Individually', 440, 'load_table_data', NOW(), NULL);
COMMIT;