call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'January', 56883);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'January', 1428);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'January', 7241);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'January', 14289);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'January', 1420);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'January', 6843);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'January', 10635);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'January', 2810);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'January', 10219);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'January', 1997);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'February', 56828);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'February', 1393);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'February', 7339);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'February', 14320);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'February', 1410);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'February', 6807);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'February', 10613);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'February', 2817);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'February', 10204);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'February', 1925);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'March', 56647);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'March', 1390);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'March', 7284);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'March', 14281);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'March', 1406);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'March', 6784);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'March', 10601);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'March', 2857);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'March', 10142);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'March', 1901);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'April', 56592);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'April', 1404);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'April', 7312);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'April', 14067);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'April', 1407);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'April', 6913);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'April', 10598);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'April', 2929);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'April', 10036);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'April', 1925);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'May', 56922);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'May', 1429);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'May', 7385);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'May', 14210);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'May', 1404);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'May', 7001);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'May', 10615);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'May', 2965);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'May', 9989);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'May', 1924);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'June', 56934);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'June', 1469);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'June', 7350);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'June', 14243);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'June', 1396);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'June', 6913);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'June', 10653);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'June', 2965);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'June', 10002);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'June', 1942);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'July', 56919);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'July', 1622);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'July', 7058);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'July', 14364);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'July', 1384);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'July', 6824);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'July', 10711);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'July', 2929);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'July', 10074);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'July', 1953);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'August', 57637);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'August', 1682);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'August', 7152);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'August', 14795);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'August', 1392);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'August', 6847);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'August', 10733);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'August', 2918);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'August', 10132);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'August', 1986);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'September', 57802);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'September', 1700);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'September', 7227);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'September', 14576);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'September', 1421);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'September', 7022);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'September', 10719);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'September', 2931);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'September', 10178);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'September', 2029);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'October', 57809);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'October', 1740);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'October', 7195);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'October', 14442);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'October', 1471);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'October', 7419);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'October', 10669);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'October', 2968);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'October', 10210);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'October', 1695);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'November', 58278);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'November', 1731);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'November', 7318);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'November', 14573);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'November', 1485);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'November', 7438);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'November', 10667);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'November', 2980);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'November', 10285);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'November', 1803);
call cat_itf.cap_services_data_census('export', 'Total Services', 2013, '', 'December', 58642);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2013, '', 'December', 1659);
call cat_itf.cap_services_data_census('export', 'Transport', 2013, '', 'December', 7554);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2013, '', 'December', 14741);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2013, '', 'December', 1464);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2013, '', 'December', 7278);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'December', 10713);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'December', 2965);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2013, '', 'December', 10402);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2013, '', 'December', 1866);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'January', 59141);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'January', 1646);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'January', 7533);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'January', 15232);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'January', 1408);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'January', 7060);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'January', 10806);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'January', 2924);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'January', 10562);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'January', 1970);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'February', 57726);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'February', 1632);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'February', 7118);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'February', 14232);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'February', 1388);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'February', 6924);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'February', 10882);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'February', 2923);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'February', 10645);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'February', 1983);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'March', 58837);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'March', 1726);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'March', 7431);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'March', 14726);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'March', 1405);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'March', 7088);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'March', 10940);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'March', 2960);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'March', 10652);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'March', 1910);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'April', 59468);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'April', 1810);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'April', 7473);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'April', 14919);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'April', 1458);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'April', 7478);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'April', 10982);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'April', 3035);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'April', 10582);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'April', 1731);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'May', 59955);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'May', 1883);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'May', 7674);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'May', 15158);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'May', 1483);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'May', 7520);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'May', 10976);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'May', 3070);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'May', 10549);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'May', 1643);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'June', 59298);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'June', 1898);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'June', 7427);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'June', 14852);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'June', 1481);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'June', 7458);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'June', 10923);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'June', 3065);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'June', 10554);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'June', 1638);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'July', 58500);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'July', 1869);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'July', 7421);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'July', 14418);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'July', 1452);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'July', 7184);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'July', 10822);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'July', 3019);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'July', 10597);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'July', 1717);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'August', 59148);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'August', 1911);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'August', 7695);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'August', 14869);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'August', 1441);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'August', 7043);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'August', 10769);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'August', 2988);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'August', 10706);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'August', 1725);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'September', 58682);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'September', 1890);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'September', 7505);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'September', 14435);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'September', 1447);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'September', 7124);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'September', 10764);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'September', 2973);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'September', 10880);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'September', 1664);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'October', 59652);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'October', 1985);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'October', 7510);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'October', 14673);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'October', 1471);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'October', 7559);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'October', 10805);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'October', 2974);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'October', 11120);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'October', 1554);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'November', 59726);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'November', 2041);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'November', 7457);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'November', 14837);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'November', 1487);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'November', 7336);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'November', 10836);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'November', 2975);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'November', 11287);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'November', 1469);
call cat_itf.cap_services_data_census('export', 'Total Services', 2014, '', 'December', 60431);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2014, '', 'December', 2097);
call cat_itf.cap_services_data_census('export', 'Transport', 2014, '', 'December', 7787);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2014, '', 'December', 14889);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2014, '', 'December', 1495);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2014, '', 'December', 7515);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'December', 10858);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'December', 2978);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2014, '', 'December', 11380);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2014, '', 'December', 1433);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'January', 59733);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'January', 1806);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'January', 7322);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'January', 14888);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'January', 1506);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'January', 7536);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'January', 10634);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'January', 3055);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'January', 11389);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'January', 1598);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'February', 59560);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'February', 1717);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'February', 7195);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'February', 14813);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'February', 1512);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'February', 7539);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'February', 10554);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'February', 3100);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'February', 11433);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'February', 1697);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'March', 59583);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'March', 1704);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'March', 7170);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'March', 14634);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'March', 1519);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'March', 7658);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'March', 10545);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'March', 3114);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'March', 11514);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'March', 1726);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'April', 59084);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'April', 1850);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'April', 7017);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'April', 14634);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'April', 1526);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'April', 7285);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'April', 10585);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'April', 3122);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'April', 11391);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'April', 1674);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'May', 59255);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'May', 1929);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'May', 7059);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'May', 14910);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'May', 1531);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'May', 7074);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'May', 10605);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'May', 3134);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'May', 11348);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'May', 1665);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'June', 59404);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'June', 1994);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'June', 6963);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'June', 14937);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'June', 1534);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'June', 7163);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'June', 10597);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'June', 3150);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'June', 11387);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'June', 1679);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'July', 59557);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'July', 1963);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'July', 6961);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'July', 14921);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'July', 1535);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'July', 7199);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'July', 10563);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'July', 3171);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'July', 11506);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'July', 1738);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'August', 59790);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'August', 1947);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'August', 6990);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'August', 14904);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'August', 1535);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'August', 7341);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'August', 10530);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'August', 3185);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'August', 11608);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'August', 1748);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'September', 59884);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'September', 1915);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'September', 6945);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'September', 15030);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'September', 1535);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'September', 7368);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'September', 10499);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'September', 3194);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'September', 11692);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'September', 1706);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'October', 60167);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'October', 1978);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'October', 7076);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'October', 14994);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'October', 1536);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'October', 7559);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'October', 10469);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'October', 3195);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'October', 11759);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'October', 1601);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'November', 60071);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'November', 2021);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'November', 6968);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'November', 14976);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'November', 1539);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'November', 7533);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'November', 10447);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'November', 3209);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'November', 11831);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'November', 1546);
call cat_itf.cap_services_data_census('export', 'Total Services', 2015, '', 'December', 60343);
call cat_itf.cap_services_data_census('export', 'Maintenance and Repair Services n.i.e.', 2015, '', 'December', 2061);
call cat_itf.cap_services_data_census('export', 'Transport', 2015, '', 'December', 6970);
call cat_itf.cap_services_data_census('export', 'Travel
(for all purposes including education) (1)', 2015, '', 'December', 14942);
call cat_itf.cap_services_data_census('export', 'Insurance Services', 2015, '', 'December', 1546);
call cat_itf.cap_services_data_census('export', 'Financial Services', 2015, '', 'December', 7713);
call cat_itf.cap_services_data_census('export', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'December', 10432);
call cat_itf.cap_services_data_census('export', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'December', 3234);
call cat_itf.cap_services_data_census('export', 'Other Business Services', 2015, '', 'December', 11909);
call cat_itf.cap_services_data_census('export', 'Government Goods and Services n.i.e. ', 2015, '', 'December', 1536);
