call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'January', 37955);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'January', 645);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'January', 7482);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'January', 8432);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'January', 4442);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'January', 1466);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'January', 3295);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'January', 2738);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'January', 7311);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'January', 2144);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'February', 37935);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'February', 634);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'February', 7626);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'February', 8439);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'February', 4393);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'February', 1425);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'February', 3243);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'February', 2764);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'February', 7288);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'February', 2122);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'March', 37938);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'March', 634);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'March', 7429);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'March', 8557);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'March', 4394);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'March', 1463);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'March', 3224);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'March', 2808);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'March', 7314);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'March', 2115);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'April', 38318);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'April', 625);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'April', 7473);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'April', 8634);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'April', 4443);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'April', 1525);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'April', 3237);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'April', 2869);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'April', 7388);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'April', 2124);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'May', 38530);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'May', 627);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'May', 7527);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'May', 8621);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'May', 4488);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'May', 1560);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'May', 3217);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'May', 2898);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'May', 7463);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'May', 2129);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'June', 38693);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'June', 626);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'June', 7547);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'June', 8732);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'June', 4531);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'June', 1528);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'June', 3164);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'June', 2893);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'June', 7539);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'June', 2132);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'July', 38483);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'July', 654);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'July', 7459);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'July', 8621);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'July', 4571);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'July', 1498);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'July', 3077);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'July', 2855);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'July', 7615);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'July', 2133);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'August', 38794);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'August', 662);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'August', 7542);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'August', 8791);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'August', 4570);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'August', 1484);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'August', 3084);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'August', 2826);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'August', 7708);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'August', 2127);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'September', 38822);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'September', 651);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'September', 7529);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'September', 8625);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'September', 4528);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'September', 1568);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'September', 3186);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'September', 2804);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'September', 7818);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'September', 2113);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'October', 39396);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'October', 585);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'October', 7637);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'October', 8845);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'October', 4446);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'October', 1676);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'October', 3382);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'October', 2792);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'October', 7943);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'October', 2092);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'November', 39519);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'November', 572);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'November', 7752);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'November', 8829);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'November', 4356);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'November', 1694);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'November', 3462);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'November', 2784);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'November', 8004);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'November', 2066);
call cat_itf.cap_services_data_census('import', 'Total Services', 2013, '', 'December', 39317);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2013, '', 'December', 571);
call cat_itf.cap_services_data_census('import', 'Transport', 2013, '', 'December', 7631);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2013, '', 'December', 8980);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2013, '', 'December', 4259);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2013, '', 'December', 1632);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2013, '', 'December', 3427);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2013, '', 'December', 2781);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2013, '', 'December', 8000);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2013, '', 'December', 2035);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'January', 38635);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'January', 568);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'January', 7623);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'January', 8706);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'January', 4154);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'January', 1574);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'January', 3277);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'January', 2783);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'January', 7933);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'January', 2018);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'February', 39270);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'February', 587);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'February', 7642);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'February', 8742);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'February', 4107);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'February', 1510);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'February', 3987);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'February', 2781);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'February', 7903);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'February', 2010);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'March', 38908);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'March', 607);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'March', 7827);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'March', 8860);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'March', 4119);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'March', 1562);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'March', 3232);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'March', 2777);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'March', 7912);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'March', 2012);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'April', 39417);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'April', 627);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'April', 7783);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'April', 9127);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'April', 4189);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'April', 1602);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'April', 3336);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'April', 2770);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'April', 7958);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'April', 2025);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'May', 39934);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'May', 627);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'May', 7877);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'May', 9396);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'May', 4222);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'May', 1638);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'May', 3411);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'May', 2768);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'May', 7959);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'May', 2035);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'June', 39968);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'June', 623);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'June', 7756);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'June', 9377);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'June', 4217);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'June', 1673);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'June', 3589);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'June', 2774);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'June', 7917);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'June', 2043);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'July', 39734);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'July', 625);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'July', 7725);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'July', 9320);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'July', 4174);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'July', 1663);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'July', 3562);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'July', 2785);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'July', 7831);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'July', 2048);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'August', 39599);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'August', 606);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'August', 7783);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'August', 9246);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'August', 4157);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'August', 1652);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'August', 3491);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'August', 2789);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'August', 7833);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'August', 2041);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'September', 39793);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'September', 623);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'September', 7869);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'September', 9200);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'September', 4165);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'September', 1688);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'September', 3518);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'September', 2785);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'September', 7924);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'September', 2021);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'October', 40489);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'October', 636);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'October', 7992);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'October', 9567);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'October', 4198);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'October', 1680);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'October', 3550);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'October', 2773);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'October', 8103);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'October', 1990);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'November', 40417);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'November', 657);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'November', 7947);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'November', 9455);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'November', 4206);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'November', 1628);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'November', 3576);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'November', 2766);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'November', 8216);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'November', 1967);
call cat_itf.cap_services_data_census('import', 'Total Services', 2014, '', 'December', 41264);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2014, '', 'December', 681);
call cat_itf.cap_services_data_census('import', 'Transport', 2014, '', 'December', 8395);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2014, '', 'December', 9792);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2014, '', 'December', 4188);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2014, '', 'December', 1634);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2014, '', 'December', 3595);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2014, '', 'December', 2763);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2014, '', 'December', 8262);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2014, '', 'December', 1953);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'January', 40371);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'January', 684);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'January', 8114);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'January', 9708);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'January', 4103);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'January', 1581);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'January', 3282);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'January', 2735);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'January', 8296);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'January', 1867);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'February', 40057);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'February', 689);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'February', 8083);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'February', 9663);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'February', 4058);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'February', 1539);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'February', 3168);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'February', 2720);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'February', 8323);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'February', 1813);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'March', 40581);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'March', 710);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'March', 8529);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'March', 9709);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'March', 4040);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'March', 1596);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'March', 3144);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'March', 2716);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'March', 8345);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'March', 1791);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'April', 40453);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'April', 704);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'April', 8076);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'April', 9830);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'April', 4048);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'April', 1654);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'April', 3276);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'April', 2732);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'April', 8324);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'April', 1810);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'May', 40623);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'May', 694);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'May', 8122);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'May', 9870);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'May', 4043);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'May', 1668);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'May', 3343);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'May', 2738);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'May', 8326);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'May', 1818);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'June', 40548);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'June', 730);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'June', 7922);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'June', 9901);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'June', 4025);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'June', 1701);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'June', 3367);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'June', 2735);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'June', 8352);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'June', 1816);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'July', 40710);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'July', 732);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'July', 7999);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'July', 10026);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'July', 3995);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'July', 1686);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'July', 3347);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'July', 2722);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'July', 8401);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'July', 1802);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'August', 40864);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'August', 736);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'August', 8090);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'August', 10143);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'August', 3968);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'August', 1644);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'August', 3335);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'August', 2716);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'August', 8442);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'August', 1790);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'September', 41373);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'September', 745);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'September', 8161);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'September', 10580);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'September', 3943);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'September', 1644);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'September', 3331);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'September', 2716);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'September', 8474);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'September', 1778);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'October', 41178);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'October', 762);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'October', 8064);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'October', 10408);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'October', 3922);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'October', 1699);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'October', 3335);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'October', 2724);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'October', 8498);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'October', 1767);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'November', 41056);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'November', 767);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'November', 8077);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'November', 10272);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'November', 3901);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'November', 1686);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'November', 3337);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'November', 2728);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'November', 8536);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'November', 1753);
call cat_itf.cap_services_data_census('import', 'Total Services', 2015, '', 'December', 41185);
call cat_itf.cap_services_data_census('import', 'Maintenance and Repair Services n.i.e.', 2015, '', 'December', 775);
call cat_itf.cap_services_data_census('import', 'Transport', 2015, '', 'December', 8038);
call cat_itf.cap_services_data_census('import', 'Travel
(for all purposes including education) (1)', 2015, '', 'December', 10415);
call cat_itf.cap_services_data_census('import', 'Insurance Services', 2015, '', 'December', 3881);
call cat_itf.cap_services_data_census('import', 'Financial Services', 2015, '', 'December', 1690);
call cat_itf.cap_services_data_census('import', 'Charges for the Use of Intellectual Property n.i.e.', 2015, '', 'December', 3336);
call cat_itf.cap_services_data_census('import', 'Telecommuni-cations, Computer, and Information Services', 2015, '', 'December', 2727);
call cat_itf.cap_services_data_census('import', 'Other Business Services', 2015, '', 'December', 8590);
call cat_itf.cap_services_data_census('import', 'Government Goods and Services n.i.e. ', 2015, '', 'December', 1734);
