DELETE FROM pht_code
WHERE client_id=1 AND type_cd = '1014';
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-01', NULL, NULL, 'Maine', 'Portland, Maine', 10, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-02', NULL, NULL, 'St Alb', 'St. Albans, Vermont', 20, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-04', NULL, NULL, 'Boston', 'Boston, Massachusetts', 30, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-05', NULL, NULL, 'Prov.', 'Providence, Rhode Island', 40, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-07', NULL, NULL, 'Ogdensb', 'Ogdensburg, New York', 50, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-09', NULL, NULL, 'Buffalo', 'Buffalo, New York', 60, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-10', NULL, NULL, 'Ny City', 'New York City, New York', 70, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-11', NULL, NULL, 'Phila.', 'Philadelphia, Pa.', 80, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-13', NULL, NULL, 'Balt.', 'Baltimore, Maryland', 90, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-14', NULL, NULL, 'Norfolk', 'Norfolk, Virginia', 100, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-15', NULL, NULL, 'Wilm Nc', 'Wilmington, N. Carolina', 110, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-16', NULL, NULL, 'Chrlstn', 'Charleston, S. Carolina', 120, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-17', NULL, NULL, 'Savannh', 'Savannah, Georgia', 130, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-18', NULL, NULL, 'Tampa', 'Tampa, Florida', 140, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-19', NULL, NULL, 'Mobile', 'Mobile, Alabama', 150, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-20', NULL, NULL, 'New Orl', 'New Orleans, Louisiana', 160, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-21', NULL, NULL, 'Port Ar', 'Port Arthur, Texas', 170, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-23', NULL, NULL, 'Laredo', 'Laredo, Texas', 180, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-24', NULL, NULL, 'El Paso', 'El Paso, Texas', 190, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-25', NULL, NULL, 'San Dgo', 'San Diego, California', 200, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-26', NULL, NULL, 'Nogales', 'Nogales, Arizona', 210, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-27', NULL, NULL, 'Los Ang', 'Los Angeles, California', 220, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-28', NULL, NULL, 'San Frn', 'San Francisco, Calif.', 230, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-29', NULL, NULL, 'Col-Snk', 'Columbia-Snake', 240, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-30', NULL, NULL, 'Seattle', 'Seattle, Washington', 250, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-31', NULL, NULL, 'Alaska', 'Anchorage, Alaska', 260, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-32', NULL, NULL, 'Hawaii', 'Honolulu, Hawaii', 270, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-33', NULL, NULL, 'Gtfalls', 'Great Falls, Montana', 280, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-34', NULL, NULL, 'Pembina', 'Pembina, North Dakota', 290, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-35', NULL, NULL, 'Minnpls', 'Minneapolis, Minnesota', 300, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-36', NULL, NULL, 'Duluth', 'Duluth Minnesota', 310, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-37', NULL, NULL, 'Milwkee', 'Milwaukee, Wisconsin', 320, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-38', NULL, NULL, 'Detroit', 'Detroit, Michigan', 330, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-39', NULL, NULL, 'Chicago', 'Chicago, Illinois', 340, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-41', NULL, NULL, 'Clevlnd', 'Cleveland, Ohio', 350, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-45', NULL, NULL, 'St. Lou', 'St. Louis, Missouri', 360, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-49', NULL, NULL, 'P. R.', 'San Juan,  Puerto Rico', 370, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-51', NULL, NULL, 'Virg Is', 'Virgin Islands of the Us', 380, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-52', NULL, NULL, 'Miami', 'Miami, Flordia', 390, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-53', NULL, NULL, 'Hou/Gal', 'Houston/Galveston, Texas', 400, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-54', NULL, NULL, 'Wash.', 'Washington, D.C.', 410, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-55', NULL, NULL, 'Dall/Fw', 'Dallas/Fort Worth, Texas', 420, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-58', NULL, NULL, 'Sav/Wlm', 'Savannah/Wilmington', 430, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-59', NULL, NULL, 'N-M-C', 'Norfolk/Mobile/Charleston', 440, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-60', NULL, NULL, 'Vessels', 'Vessels Under Own Power', 450, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-70', NULL, NULL, 'Arb Dst', 'Low Value Shipments', 460, 'load_table_data', NOW(), NULL);
INSERT INTO pht_code (client_id, type_cd, code, parent_cd, ext_code, description, description_long, list_order, created_by, insert_dt, expire_dt)
VALUES (1, 1014, '1014-80', NULL, NULL, 'Mail', 'Mail Shipments', 470, 'load_table_data', NOW(), NULL);
COMMIT;